# Generated by Django 4.0.3 on 2022-03-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
