# Generated by Django 4.0.3 on 2022-03-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order',
            new_name='order_id',
        ),
    ]
