# Generated by Django 4.0.3 on 2022-03-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_order_orderdetail_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
    ]
